CREATE TABLE [dm_Product] (
[Product_pk] INT NOT NULL IDENTITY
,[Product_nk] [varchar](20) --Coditem
,[Description] [varchar](100) 
,[StorageUnit] [varchar](4)
,[StorageConsumption] [varchar](4)
,[Version] [int]
,[MaterialType] [varchar](4)
,[UserNumField1] [float]
,[UserNumField2] [float]
,[UserNumField3] [float]
,[Altura] [int]
,[Largura] [int]
,[Gramatura] [float]
,[ObjID_ContasDeCusto] [float]
,[Apelido] [varchar](20)
,[ObjID_TBCustoMat] [float]
,[ObjID] [float]
,[UnidadeCusto] [varchar](4)
,[PercIPI] [float]
,[PercICMS] [float]
,[ConsumoMedio] [float]
,[EstoqueMinimo] [float]
,[PrazoReposicao] [float]
,[Observacoes] [varchar](255)
,[RequerLote] [char](1)
,[CodGrupo] [varchar](20)
,[TipoDeItem] [char](1)
,[CodContaFinanceira] [int]
,[ClassificacaoFiscal] [varchar](20)
,[QtdeMesesConsumoMedio] [int]
,[EstoqueMininoEmDias] [char](1)
,[Status] [char](1)
,[RequerOP] [char](1)
,[EstoqueMinimoReal] [float]
,[OrigemItem] [char](1)
,[UtilizadoOrcamento] [char](1)
,[MaterialFornecido] [char](1)
,[Venda] [char](1)
,[PesoEMKG] [float]
,[usr_comprimento_cx] [int]
,[usr_largura_cx] [int]
,[usr_altura_cx] [int]
,[usr_amostra] [char](1)
,[RequeLocalizacao] [char](1)
,[CodEstrutura] [varchar](12)
,[ObjIDSuporte] [float]
,[DtInativacao] [datetime]
,[CodFornecedor] [varchar](30)
,[usr_codlancamento] [char](3)
,[ObjidTabComissao] [float]
,[Usr_QtdnaFaca] [int]
,[usr_ArqInterno] [char](50)
,[Usr_ArqFornecedor] [char](50)
,[Usr_inscnafaca] [char](50)
,[usr_dimensmadeira] [char](50)
,[usr_pinca] [char](50)
,[usrcliente] [char](50)
,[usr_facaoriginal] [char](50)
,[usr_contacredito] [char](20)
,[usr_contadebito] [char](20)
,[PermitirNFSemPedCompra] [char](1)
,[BloqueadoParaInventario] [char](1)
,[Usr_tipocliche] [varchar](40)
,[DiasDesativar] [int]
,[DataInclusao] [datetime]
,[Usr_qtdetinta01] [float]
,[Usr_qtdetinta02] [float]
,[Usr_qtdetinta03] [float]
,[Usr_qtdetinta04] [float]
,[Usr_qtdetinta05] [float]
,[Usr_tinta01] [varchar](80)
,[Usr_tinta02] [varchar](80)
,[Usr_tinta03] [varchar](80)
,[Usr_tinta04] [varchar](80)
,[Usr_tinta05] [varchar](80)
,[Usr_tipocorte] [varchar](10)
,[EstoqueMinimoQuantidade] [float]
,[EstoqueMaximo] [float]
,[FormaCalculoEstoqueMaximo] [smallint]
,[FormaCalculoNecessidadeCompra] [smallint]
,[FormaSugestaoQtdSerComprada] [char](1)
,[EstoqueMaximoEmDias] [float]
,[EstoqueMaximoReal] [float]
,[ObjIdLocalEstoquePadrao] [float]
,[CreditaImposto] [smallint]
,[ExibicaoEstoqueMaximo] [int]
,[Usr_Fsc] [char](1)
,[Usr_FscEspecie] [varchar](80)
,[usr_areacart] [float]
,[usr_medcart] [varchar](20)
,[ObjIDEspecificacaoApropriacao] [float]
,[ItemInventariado] [char](1)
,[ReterImpostos] [int]
,[Usr_CruzaCruz] [char](50)
,[UtilizarControleVolumes] [char](1)
,[usr_fretesaida] [char](1)
,[usr_freteentrada] [char](1)
,[usr_tipotinta] [varchar](20)
,[usr_monitor] [varchar](50)
,[usr_nsmonitor] [varchar](80)
,[usr_tpmb] [varchar](30)
,[usr_tponboard] [varchar](100)
,[usr_mdmb] [varchar](50)
,[usr_mcmb] [varchar](50)
,[usr_tpsocket] [varchar](30)
,[usr_processador] [varchar](50)
,[usr_tpmemoria] [varchar](30)
,[usr_mcmemoria] [varchar](30)
,[usr_qtdmemoria] [varchar](30)
,[usr_clkmemoria] [varchar](30)
,[usr_mchd] [varchar](30)
,[usr_modhd] [varchar](30)
,[usr_tphd] [varchar](30)
,[usr_mcvdof] [varchar](30)
,[usr_mdvdof] [varchar](30)
,[usr_tpsocketvdof] [varchar](30)
,[usr_mcrede] [varchar](30)
,[usr_mdrede] [varchar](30)
,[usr_vlrede] [varchar](30)
,[usr_mcaudio] [varchar](30)
,[usr_mdaudio] [varchar](30)
,[usr_tpaudio] [varchar](30)
,[usr_mcmodem] [varchar](30)
,[usr_mdmodem] [varchar](30)
,[usr_vlmodem] [varchar](30)
,[usr_qtdbaias] [varchar](30)
,[usr_fonte] [varchar](30)
,[usr_tpgabinete] [varchar](30)
,[usr_sndisquete] [varchar](1)
,[usr_tp1cd] [varchar](30)
,[usr_vl1cd] [varchar](30)
,[usr_os] [varchar](100)
,[usr_office] [varchar](100)
,[usr_outrosapl] [varchar](250)
,[usr_dtcompra] [datetime]
,[usr_garantiacompra] [varchar](30)
,[usr_nrnfcompra] [varchar](20)
,[usr_areaPA] [float]
,[usr_CLAPA] [varchar](50)
,[usr_naturezafiscal] [varchar](1)
,[usr_host] [varchar](12)
,[usr_user] [varchar](25)
,[DiametroPadrao] [numeric](15,0)
,[PesoMaximo] [numeric](18,3)
,[PesoMinimo] [numeric](18,3)
,[UnidadeDiametroPadrao] [varchar](4)
,[UnidadePesoMaximo] [varchar](4)
,[UnidadePesoMinimo] [varchar](4)
,[MovimentacaoPorPallet] [char](1)
,[DigitosEtiqueta] [int]
,[DigitosEmbalagem] [int]
,[DigitosEmbalagemDec] [int]
,[PercentualSolido] [float]
,[ExplodirItens] [char](1)
,[UnidadeLote] [varchar](4)
,[EntradaPorEtiqueta] [char](1)
,[DescrNota] [varchar](400)
,[DestacarComponenteNaNota] [char](1)
,[QtdEmbalagem] [float]
,[RequerSeparacao] [char](1)
,[UnidadeEmbLote] [varchar](4)
,[usr_mnt_mc] [char](30)
,[usr_mnt_mod] [char](50)
,[usr_mnt_tam] [char](3)
,[usr_mnt_nrserie] [char](50)
,[usr_mnt_nrmod] [char](30)
,[usr_mnt_dtfabric] [datetime]
,[usr_codbarras] [varchar](50)
,[usr_tamhd] [varchar](5)
,[usr_macaddress] [varchar](50)
,[usr_mc1cd] [char](30)
,[usr_mod1cd] [char](30)
,[IdNaturezaFinanceira] [int]
,[usr_tipocola] [varchar](50)
,[ComprasRateioFinanceiro] [int]
,[ObjidUnidadeNegocio] [float]
,[Usr_TipoVerniz] [varchar](50)
,[CreditaIPI] [smallint]
,[CreditaICMS] [smallint]
,[usr_tipoaplicacao] [varchar](50)
,[usr_apelido] [varchar](100)
,[usr_destacador] [varchar](50)
,[usr_pertinax] [char](1)
,[usr_contagem] [float]
,[usr_comprimento_cx_ext] [int]
,[usr_largura_cx_ext] [int]
,[usr_altura_cx_ext] [int]
,[usr_altura_plet] [int]
,[usr_largura_plet] [int]
,[usr_comprimento_plet] [int]
,[usr_linha_tintas] [varchar](50)
,[usr_formula_tintas] [varchar](50)
,[usr_furacao] [varchar](10)
,[usr_pecas] [varchar](50)
,[usr_dizeresbraile] [varchar](200)
,[usr_localaplic] [varchar](100)
,[QtdeDiasValidade] [int]
,[usr_descop] [varchar](40)
,[sped_origem] [varchar](30)
,[usr_perccliente] [int]
,[geraopparapedidovenda] [int]
,[naogerapedlibprod] [int]
,[PermiteSepararLotesDiff] [int]
,[usr_comprimento] [varchar](50)
,[usr_largura] [varchar](50)
,[usr_tipoonda] [varchar](50)
,[usr_papelcapa] [varchar](50)
,[usr_grmpapelcapa] [varchar](50)
,[usr_papelmiolo] [varchar](50)
,[usr_grmpapelmiolo] [varchar](50)
,[usr_sentidoonda] [varchar](50)
,[usr_obs] [varchar](200)
,[usr_descexterno] [varchar](100)
,[usr_promocional] [char](1)
,[usr_percclienteop] [int]
,[usr_ciap] [char](2)
,[Usr_qtdetinta06] [float]
,[Usr_tinta06] [varchar](80)
,[usr_Meta_Maq1] [varchar](10)
,[usr_Meta_Maq2] [varchar](10)
,[usr_Meta_Maq3] [varchar](10)
,[usr_Meta_Maq4] [varchar](10)
,[usr_Meta_Maq5] [varchar](10)
,[usr_Meta_Maq6] [varchar](10)
,[usr_Meta_Maq7] [varchar](10)
,[usr_Meta_Maq8] [varchar](10)
,[usr_Meta_Maq9] [varchar](10)
,[controlarrastreabilidade] [char](1)
,[IncluirItemReqMat] [char](1)
,[itemfsc] [char](1)
,[itemimune] [char](1)
,[tipopublicacao] [int]
,[LoteMinimoProducao] [float]
,[TipoItemSped] [varchar](2)
,[NumItem] [int]
,[usr_Meta_Maq10] [varchar](10)
,[usr_Meta_Maq11] [varchar](10)
,[usr_especificacoes] [varchar](50)
,[Usr_percfscclaim] [int]
,[Usr_kanban] [char](1)
,[usr_CodigoEstoqueMatriz] [varchar](100)
,[usr_CodigoEstoqueFilial] [varchar](100)
,[IdPrdClass] [int]
,[OrigemMercadoria] [smallint]
,[usr_declaracaofsc] [varchar](30)
,[CodigoFaca] [varchar](30)
,[Usr_TonerCompativel] [varchar](50)
,[usr_corporacao] [varchar](100)
,[usr_diasestoqueCP] [int]
,[usr_diasestoquekanban] [int]
,[usr_DescFita] [varchar](255)
,[usr_LargFita] [varchar](100)
,[usr_piloto] [char](1)
,[usr_CompEmbalagem] [char](30)
,[usr_GabEmbalagem] [char](30)
,[CalculaEstoqueMaxMinPorLocal] [char](1)
,[IdCGroupValue] [int]
,[InsUser] [varchar](41)
,[usr_reducaoPerdas] [char](1)
,[CalcConsumoOrcExcel] [char](1)
,[CreditaICMSST] [smallint]
,[MargemPadraoACR] [float]
,[TipoItemFatRem] [smallint]
,[TipoItemFatura] [smallint]
,[TipoItemRemessa] [smallint]
,[usr_StatusDtValidade] [char](20)
,[usr_alimenticio] [varchar](3)
,[usr_tipoembalagem] [varchar](20)
,[usr_TipoFrete] [varchar](20)
,[DataAlteracao] [datetime]
,[UpdUser] [varchar](40)
) ON [PRIMARY]